openapi: 3.2.0
info:
  title: Tradeshift External Dx Category Document Validation Validators Find API
  version: 1.0.0
servers:
- url: https://api.tradeshift.com/tradeshift
tags:
- name: dx-category--document-validation-validators_find
paths:
  /rest/external/document-validation/validation/groups/{groupId}:
    get:
      tags:
      - dx-category--document-validation-validators_find
      summary: Gets a validator group
      description: Gets a validator group definition
      operationId: get-rest-external-document-validation-validation-groups-groupid
      parameters:
      - name: groupId
        in: path
        description: UUID of the validator group to get
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDef'
